POST http://localhost:3000/api/tournament
Content-Type: application/json
Authorization: Bearer put-your-jwt-token-here

{
  "buyin": 20,
  "count": 2,
  "players_0_name": "saeid",
  "players_0_rebuys": 1,
  "players_0_prize": 60,
  "players_1_name": "eva",
  "players_1_rebuys": 1,
  "players_1_prize": 20
}


###


GET http://localhost:3000/api/tournament
Content-Type: application/json


###


POST http://localhost:3000/api/players
Content-Type: application/json

{
  "name": "Saeid"
}
