// returns all players from prod
GET http://localhost:3000/api/players?event_id=677cc26c5462214b2a1ac7a0
Content-Type: application/json


// returns a player by id
GET http://localhost:3000/api/players/654b3fc05c0cb6103ea76d74

###

// returns a player by name
GET http://localhost:3000/api/players/name/Goscha

###

// adds a new player
POST http://localhost:3000/api/players
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InNtb2hhZGplciIsImV4cCI6MTczNDM2Mjc2OH0.Jgg5QJ28rc5X0L350i4oW4lAxKdFH2cTlnZn2P7HTlU

{
  "name": "Abba"
}

###

// change an existing player's name
POST http://localhost:3000/api/players
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InNtb2hhZGplciIsImV4cCI6MTczNDM2Mjc2OH0.Jgg5QJ28rc5X0L350i4oW4lAxKdFH2cTlnZn2P7HTlU

{
  "player_id": "654b3fc05c0cb6103ea76d74",
  "name": "Goscha123"
}

###

// delete a player by name
DELETE http://localhost:3000/api/players/name/Tester
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InNtb2hhZGplciIsImV4cCI6MTczNDM2Mjc2OH0.Jgg5QJ28rc5X0L350i4oW4lAxKdFH2cTlnZn2P7HTlU

{}
